'use client'

import { useState, useEffect, useCallback } from 'react'
import Link from 'next/link'
import { Play, Loader2, CheckCircle, XCircle, Clock, Mic2, ListMusic, Settings, X } from 'lucide-react'
import StepByStepModal from './StepByStepModal'
import PricingModal from './PricingModal'
import ProPlanTooltip from './ProPlanTooltip'
import AdminCreditManager from './AdminCreditManager'
import { apiGet } from '@/backend/lib/api-client'

interface Podcast {
  id: string
  title: string
  description: string
  audioUrl?: string
  duration?: number
  status: string
  createdAt: string
  publishedAt?: string
  isAutoGenerated?: boolean
}

export default function PodcastGenerator() {
  const [isGenerating, setIsGenerating] = useState(false)
  const [podcasts, setPodcasts] = useState<Podcast[]>([])
  const [showModal, setShowModal] = useState(false)
  const [showPricingModal, setShowPricingModal] = useState(false)
  const [showProPlanTooltip, setShowProPlanTooltip] = useState(false)
  const [showAdminManager, setShowAdminManager] = useState(false)
  const [credits, setCredits] = useState<number>(0)
  const [currentTime, setCurrentTime] = useState(new Date())
  const [showTooltip, setShowTooltip] = useState(false)
  const [isAdmin, setIsAdmin] = useState(false)

  // 페이지 로드 시 모달 상태 복구
  useEffect(() => {
    fetchPodcasts()
    fetchCredits()
    checkAdminPermission()
    
    // localStorage에서 모달 상태 복구
    const savedModalState = localStorage.getItem('podcast_modal_open')
    if (savedModalState === 'true') {
      setShowModal(true)
      setIsGenerating(true)
      console.log('🔄 모달 상태 복구: 열림')
    }

    // 1분마다 현재 시간 업데이트 (카운트다운용)
    const timer = setInterval(() => {
      setCurrentTime(new Date())
    }, 60000)

    return () => clearInterval(timer)
  }, [])

  const generatePodcast = useCallback(async () => {
    setIsGenerating(true)
    setShowModal(true)
    // 모달 상태 저장
    localStorage.setItem('podcast_modal_open', 'true')
    console.log('💾 모달 상태 저장: 열림')
  }, [])

  const handleModalComplete = useCallback((podcastId: string) => {
    setShowModal(false)
    setIsGenerating(false)
    // 모달 상태 제거
    localStorage.removeItem('podcast_modal_open')
    console.log('🗑️ 모달 상태 제거: 완료')
    fetchPodcasts()
    fetchCredits()
  }, [])

  const handleModalClose = useCallback(() => {
    setShowModal(false)
    setIsGenerating(false)
    // 모달 상태 제거
    localStorage.removeItem('podcast_modal_open')
    console.log('🗑️ 모달 상태 제거: 닫기')
  }, [])

  const fetchPodcasts = async () => {
    try {
      const { data } = await apiGet<Podcast[]>('/api/podcast')
      
      if (data) {
        setPodcasts(data)
      }
    } catch (error) {
      console.error('Error fetching podcasts:', error)
    }
  }

  const fetchCredits = async () => {
    try {
      const response = await fetch('/api/user/credits')
      if (response.ok) {
        const data = await response.json()
        setCredits(data.credits)
        
        // 크레딧이 10개 이하면 tooltip 표시
        if (data.credits <= 10 && data.credits > 0) {
          setShowTooltip(true)
          // 5초 후 tooltip 자동 숨김
          setTimeout(() => setShowTooltip(false), 5000)
        }
        
        // 크레딧이 0이면 Pro 플랜 툴팁 표시
        if (data.credits === 0) {
          setShowProPlanTooltip(true)
        }
      }
    } catch (error) {
      console.error('Error fetching credits:', error)
    }
  }

  const checkAdminPermission = async () => {
    try {
      const response = await fetch('/api/admin/check-permission')
      if (response.ok) {
        const data = await response.json()
        setIsAdmin(data.isAdmin)
      }
    } catch (error) {
      console.error('Error checking admin permission:', error)
    }
  }

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'completed':
        return (
          <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-semibold bg-primary-100 text-brand">
            <CheckCircle className="w-3 h-3 mr-1" />
            완료
          </span>
        )
      case 'failed':
        return (
          <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-semibold bg-red-100 text-red-700">
            <XCircle className="w-3 h-3 mr-1" />
            실패
          </span>
        )
      case 'processing':
        return (
          <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-semibold bg-blue-100 text-blue-700">
            <Loader2 className="w-3 h-3 mr-1 animate-spin" />
            처리중
          </span>
        )
      default:
        return (
          <span className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-semibold bg-gray-100 text-gray-700">
            대기중
          </span>
        )
    }
  }

  const formatDuration = (seconds?: number) => {
    if (!seconds) return '알 수 없음'
    const minutes = Math.floor(seconds / 60)
    const remainingSeconds = seconds % 60
    return `${minutes}:${remainingSeconds.toString().padStart(2, '0')}`
  }

  const getTimeUntilPublish = (publishedAt: string) => {
    const publishTime = new Date(publishedAt)
    const diff = publishTime.getTime() - currentTime.getTime()
    
    if (diff <= 0) return null
    
    const hours = Math.floor(diff / (1000 * 60 * 60))
    const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60))
    
    if (hours > 0) {
      return `${hours}시간 ${minutes}분 후 공개`
    } else {
      return `${minutes}분 후 공개`
    }
  }

  const isPodcastPublished = (publishedAt?: string) => {
    if (!publishedAt) return true
    return new Date(publishedAt).getTime() <= currentTime.getTime()
  }

  return (
    <div className="px-4 py-6 space-y-6">
      {/* 크레딧 표시 */}
      <div className="relative">
        <div 
          className="app-card p-4 bg-gradient-to-r from-amber-50 to-amber-100 border border-amber-200 fade-in cursor-pointer hover:shadow-lg transition-all"
          onClick={() => setShowPricingModal(true)}
        >
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <div className="w-8 h-8 bg-gradient-to-br from-amber-400 to-amber-500 rounded-lg flex items-center justify-center">
                <span className="text-white font-bold text-sm">💳</span>
              </div>
              <div>
                <p className="text-sm font-medium text-gray-900">남은 크레딧</p>
                <p className="text-xs text-gray-600">매일 자동으로 팟캐스트를 생성합니다</p>
              </div>
            </div>
          <div className="text-right">
            <div className="flex items-center space-x-2">
              <p className="text-2xl font-bold text-amber-600">{credits}</p>
              <p className="text-xs text-gray-500">개</p>
              {isAdmin && (
                <button
                  onClick={() => setShowAdminManager(true)}
                  className="w-8 h-8 bg-blue-500 hover:bg-blue-600 rounded-lg flex items-center justify-center transition-colors"
                  title="관리자 크레딧 관리"
                >
                  <Settings className="w-4 h-4 text-white" />
                </button>
              )}
            </div>
          </div>
          </div>
          {credits === 0 && (
            <div className="mt-3 p-2 bg-red-50 border border-red-200 rounded-lg">
              <p className="text-xs text-red-700">⚠️ 크레딧이 부족합니다. 팟캐스트를 생성할 수 없습니다.</p>
            </div>
          )}
        </div>

        {/* Tooltip - 담백한 스타일 */}
        {showTooltip && credits <= 10 && credits > 0 && (
          <div className="absolute top-full left-0 right-0 mt-2 z-10 px-2">
            <div className="bg-white border border-gray-300 rounded-lg shadow-lg px-4 py-3">
              <div className="flex items-start space-x-3">
                <div className="flex-1 min-w-0">
                  <p className="font-medium mb-1 text-gray-900">크레딧이 얼마 남지 않았어요</p>
                  <p className="text-sm text-gray-600">클릭해서 플랜을 확인하세요</p>
                </div>
                <button 
                  onClick={(e) => {
                    e.stopPropagation()
                    setShowTooltip(false)
                  }}
                  className="w-6 h-6 flex items-center justify-center rounded hover:bg-gray-100 transition-colors flex-shrink-0"
                  aria-label="닫기"
                >
                  <X className="w-4 h-4 text-gray-500" />
                </button>
              </div>
              {/* 화살표 */}
              <div className="absolute -top-1 left-6 w-2 h-2 bg-white border-l border-t border-gray-300 rotate-45"></div>
            </div>
          </div>
        )}
      </div>

      {/* 생성 버튼 카드 */}
      <div className="app-card p-6 bg-gradient-to-br from-brand to-brand-light text-white fade-in">
        <div className="flex items-center space-x-3 mb-4">
          <div className="w-12 h-12 bg-white/20 rounded-xl flex items-center justify-center backdrop-blur-sm">
            <Mic2 className="w-6 h-6" />
          </div>
          <div>
            <h2 className="text-xl font-bold">새 팟캐스트</h2>
            <p className="text-sm text-white/80">AI로 팟캐스트 만들기</p>
          </div>
        </div>
        
        <p className="text-sm text-white/90 mb-5 leading-relaxed">
          선택한 유튜브 플레이리스트에서 최근 동영상들의 자막을 분석하여 
          AI가 자동으로 팟캐스트를 생성합니다.
        </p>
        
        <button
          onClick={generatePodcast}
          disabled={isGenerating || credits === 0}
          className="w-full bg-white text-brand px-6 py-4 rounded-xl font-bold transition-all app-button disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center space-x-2"
        >
          {isGenerating ? (
            <>
              <Loader2 className="h-5 w-5 animate-spin" />
              <span>팟캐스트 생성 중...</span>
            </>
          ) : credits === 0 ? (
            <>
              <XCircle className="h-5 w-5" />
              <span>크레딧 부족</span>
            </>
          ) : (
            <>
              <Play className="h-5 w-5" />
              <span>팟캐스트 생성하기</span>
            </>
          )}
        </button>
      </div>

      {/* 팟캐스트 목록 */}
      <div className="fade-in">
        <div className="flex items-center space-x-2 mb-4 px-2">
          <ListMusic className="w-5 h-5 text-gray-600" />
          <h3 className="text-lg font-bold text-gray-900">내 팟캐스트</h3>
          <span className="text-sm text-gray-500">({podcasts.length})</span>
        </div>
        
        {podcasts.length === 0 ? (
          <div className="app-card p-8 text-center">
            <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-3">
              <Mic2 className="w-8 h-8 text-gray-400" />
            </div>
            <p className="text-gray-500 text-sm">아직 생성된 팟캐스트가 없습니다.</p>
            <p className="text-gray-400 text-xs mt-1">위 버튼을 눌러 첫 팟캐스트를 만들어보세요!</p>
          </div>
        ) : (
          <div className="space-y-3">
            {podcasts.map((podcast) => (
              <div key={podcast.id} className="app-card p-4 hover:shadow-md transition-all">
                <div className="space-y-3">
                  <div className="flex items-start justify-between">
                    <div className="flex-1 min-w-0">
                      <h4 className="font-bold text-gray-900 mb-1 truncate">{podcast.title}</h4>
                      <p className="text-sm text-gray-600 line-clamp-2">{podcast.description}</p>
                    </div>
                    <div className="ml-2 flex-shrink-0">
                      {getStatusBadge(podcast.status)}
                    </div>
                  </div>
                  
                  <div className="flex items-center space-x-4 text-xs text-gray-500">
                    <span className="flex items-center space-x-1">
                      <Clock className="w-3 h-3" />
                      <span>{new Date(podcast.createdAt).toLocaleDateString('ko-KR')}</span>
                    </span>
                    {podcast.duration && (
                      <span className="flex items-center space-x-1">
                        <Mic2 className="w-3 h-3" />
                        <span>{formatDuration(podcast.duration)}</span>
                      </span>
                    )}
                    {podcast.isAutoGenerated && (
                      <span className="px-2 py-0.5 bg-blue-100 text-blue-700 rounded text-xs font-medium">
                        자동생성
                      </span>
                    )}
                  </div>
                  
                  {/* 공개 시간 카운트다운 */}
                  {podcast.publishedAt && !isPodcastPublished(podcast.publishedAt) && (
                    <div className="pt-2">
                      <div className="p-3 bg-gradient-to-r from-blue-50 to-blue-100 border border-blue-200 rounded-lg">
                        <div className="flex items-center space-x-2">
                          <Clock className="w-4 h-4 text-blue-600" />
                          <div>
                            <p className="text-sm font-medium text-blue-900">
                              {getTimeUntilPublish(podcast.publishedAt)}
                            </p>
                            <p className="text-xs text-blue-700">
                              {new Date(podcast.publishedAt).toLocaleString('ko-KR', {
                                month: 'long',
                                day: 'numeric',
                                hour: '2-digit',
                                minute: '2-digit'
                              })}에 공개됩니다
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  )}
                  
                  {/* 오디오 플레이어 */}
                  {podcast.status === 'completed' && podcast.audioUrl && isPodcastPublished(podcast.publishedAt) && (
                    <div className="pt-2">
                      <audio controls className="w-full h-10" style={{borderRadius: '8px'}}>
                        <source src={podcast.audioUrl} type="audio/mpeg" />
                        브라우저가 오디오를 지원하지 않습니다.
                      </audio>
                    </div>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      <StepByStepModal
        isOpen={showModal}
        onClose={handleModalClose}
        onComplete={handleModalComplete}
      />

      <PricingModal
        isOpen={showPricingModal}
        onClose={() => setShowPricingModal(false)}
      />

      <ProPlanTooltip
        isVisible={showProPlanTooltip}
        onClose={() => setShowProPlanTooltip(false)}
        credits={credits}
      />

      <AdminCreditManager
        isVisible={showAdminManager}
        onClose={() => setShowAdminManager(false)}
      />
    </div>
  )
}
