-- AlterTable
ALTER TABLE "Podcast" ADD COLUMN     "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "publishedAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "UserSettings" ADD COLUMN     "credits" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN     "deliveryTimeHour" INTEGER NOT NULL DEFAULT 8,
ADD COLUMN     "deliveryTimeMinute" INTEGER NOT NULL DEFAULT 0;
